version: '2.1'

services:
    pdns-mailcow:
      image: andryyy/mailcow-dockerized:pdns
      depends_on:
        mysql-mailcow:
          condition: service_healthy
      volumes:
        - ./data/conf/pdns/:/etc/powerdns/
      hostname: pdns
      restart: always
      networks:
        sslserver-network:
          ipv4_address: 172.22.1.254
          aliases:
            - pdns

    mysql-mailcow:
      image: mariadb:10.1
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--host", "localhost", "--silent"]
        interval: 10s
        timeout: 30s
        retries: 5
      hostname: sequel
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      environment:
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      networks:
        sslserver-network:
          aliases:
            - mysql

    redis-mailcow:
      image: redis
      depends_on:
        - pdns-mailcow
      volumes:
        - redis-vol-1:/data/
      hostname: redis
      restart: always
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      networks:
        sslserver-network:
          aliases:
            - redis

    rspamd-mailcow:
      image: andryyy/mailcow-dockerized:rspamd
      depends_on:
        - nginx-mailcow
      hostname: rspamd
      volumes:
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:ro
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:ro
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - dkim-vol-1:/data/dkim
        - rspamd-vol-1:/var/lib/rspamd
      restart: always
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      networks:
        sslserver-network:
          ipv4_address: 172.22.1.253
          aliases:
            - rspamd

    php-fpm-mailcow:
      image: andryyy/mailcow-dockerized:phpfpm
      command: "php-fpm -d date.timezone=${TZ}"
      depends_on:
        - pdns-mailcow
      hostname: php
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - dkim-vol-1:/data/dkim
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      restart: always
      networks:
        sslserver-network:
          aliases:
            - phpfpm

    sogo-mailcow:
      image: andryyy/mailcow-dockerized:sogo
      depends_on:
        - pdns-mailcow
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
      dns:
        - 172.22.1.254
      hostname: sogo
      dns_search: sslserver-network
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
        - /usr/lib/GNUstep/SOGo/WebServerResources/
      restart: always
      networks:
        sslserver-network:
          ipv4_address: 172.22.1.252
          aliases:
            - sogo

    rmilter-mailcow:
      image: andryyy/mailcow-dockerized:rmilter
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/rmilter/:/etc/rmilter.conf.d/:ro
      restart: always
      hostname: rmilter
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      networks:
        sslserver-network:
          aliases:
            - rmilter

    dovecot-mailcow:
      image: andryyy/mailcow-dockerized:dovecot
      depends_on:
        - pdns-mailcow
      hostname: dovecot
      volumes:
        - ./data/conf/dovecot:/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - ./data/conf/sogo/:/etc/sogo/
        - vmail-vol-1:/var/vmail
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      ports:
        - "${IMAP_PORT:-143}:143"
        - "${IMAPS_PORT:-993}:993"
        - "${POP_PORT-110}:110"
        - "${POPS_PORT:-995}:995"
        - "${SIEVE_PORT:-4190}:4190"
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        sslserver-network:
          aliases:
            - dovecot

    postfix-mailcow:
      image: andryyy/mailcow-dockerized:postfix
      depends_on:
        - pdns-mailcow
      hostname: postar
      volumes:
        - ./data/conf/postfix:/opt/postfix/conf
        - ./data/assets/ssl:/etc/ssl/mail/:ro
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      ports:
        - "${SMTP_PORT:-25}:25"
        - "${SMTPS_PORT:-465}:465"
        - "${SUBMISSION_PORT:-587}:587"
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      networks:
        sslserver-network:
          aliases:
            - postfix

    memcached-mailcow:
      image: memcached
      depends_on:
        - pdns-mailcow
      restart: always
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      networks:
        sslserver-network:
          aliases:
            - memcached

    nginx-mailcow:
      depends_on:
        - sogo-mailcow
        - php-fpm-mailcow
      image: nginx:mainline
      hostname: web
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/listen.template > /etc/nginx/conf.d/listen.active && nginx -g 'daemon off;'"
      environment:
        - HTTPS_PORT=${HTTPS_PORT:-443}
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
      dns:
        - 172.22.1.254
      dns_search: sslserver-network
      ports:
        - "${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      restart: always
      networks:
        sslserver-network:
          aliases:
            - nginx

networks:
  sslserver-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24

volumes:
  vmail-vol-1:
  mysql-vol-1:
  dkim-vol-1:
  redis-vol-1:
  rspamd-vol-1:
